### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by fkrauthan** [elierotenberg/react-nexus#4]
I have a question regarding this framework. One of the common things a webapp has is authentication. How would I handle authentication with this framework? 

Two things:
* Authentication with a session?
* Authentication with something more complex like OAuth1 / OAuth2

And how would I handle a server site request for an authenticated user? (E.g. User logs in and press F5 to reload the whole page).

Are there any solutions for that already (Maybe I just missed them?) Or is there anything planned to support that?

**Comment by elierotenberg** [comment]
Authentication is now out of the scope of React Nexus.

However, I will be publishing guidelines and examples on how to implement authentication in a React Nexus idomatic way using Flux over the Wire.
